#!/usr/bin/env sh

MAIN_BRANCH='master'
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ $CURRENT_BRANCH != $MAIN_BRANCH ]]; then
  echo "Please update docs only from the $MAIN_BRANCH branch"
  exit 1
fi

if [[ -z $(git status --porcelain) ]];
then
  git checkout gh-pages && git reset master --hard  && \
  yarn doc && git add ./docs &&                        \
  git commit -m "docs: updating to latest API" &&      \
  git push origin gh-pages &&                          \
  git checkout master
else
    echo "Please commit any changes before updating docs."
    git status
fi
